services:
  train_pipeline:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - graph
    - gASVLAEAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMC0dyYXBoT3V0cHV0lJOUKYGUfZQojARuYW1llIwIcmV0dXJuLjCUjAZpb3R5cGWUjARGSUxFlIwGc291cmNllGgBjApEYXRhU291cmNllJOUKYGUfZQojAtub2RlX291dHB1dJRoAYwNTm9kZU91dHB1dFJlZpSTlCmBlH2UKIwJbm9kZV9uYW1llIwFdHJhaW6UjAtvdXRwdXRfbmFtZZSMBnJldHVybpR1YowLZ3JhcGhfaW5wdXSUTnVidWJoAymBlH2UKGgGjAhyZXR1cm4uMZRoCIwJREFUQUZSQU1FlGgKaAwpgZR9lChoD2gRKYGUfZQoaBSMCGV2YWx1YXRllGgWjAZyZXR1cm6UdWJoGE51YnViZS4=
    depends_on:
      train_pipeline.clean:
        condition: service_completed_successfully
      train_pipeline.evaluate:
        condition: service_completed_successfully
      train_pipeline.infer_pipeline.sentiment:
        condition: service_completed_successfully
      train_pipeline.infer_pipeline.translate_1:
        condition: service_completed_successfully
      train_pipeline.train:
        condition: service_completed_successfully
    image: pircli-build:588ffbcf-ac3a-4408-8b47-1f9b41b1a682
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_train_dataset:?err}:/mnt/graph_inputs/train_dataset
    - ${INPUT_translate_model:?err}:/mnt/graph_inputs/translate_model
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
    - ${OUTPUT:?err}:/mnt/graph_outputs
  train_pipeline.clean:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASV0AEAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjAVjbGVhbpSMBmNvbmZpZ5R9lIwGaW5wdXRzlF2UaACMCU5vZGVJbnB1dJSTlCmBlH2UKGgFjAdkYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojAtub2RlX291dHB1dJROjAtncmFwaF9pbnB1dJSMDXRyYWluX2RhdGFzZXSUdWJ1YmGMB291dHB1dHOUXZRoAIwKTm9kZU91dHB1dJSTlCmBlH2UKGgFjAZyZXR1cm6UaBCMCURJUkVDVE9SWZR1YmGMCmVudHJ5cG9pbnSUaACMCkVudHJ5cG9pbnSUk5QpgZR9lCiMB3ZlcnNpb26UjAJ2MZSMB2hhbmRsZXKUjBVleGFtcGxlLmV4YW1wbGU6Y2xlYW6UjAdydW50aW1llIwKcHl0aG9uOjMuOJSMB2NvZGV1cmmUTowFaW1hZ2WUjDFwaXJjbGktYnVpbGQ6NTg4ZmZiY2YtYWMzYS00NDA4LThiNDctMWY5YjQxYjFhNjgylHVijAlmcmFtZXdvcmuUTnViLg==
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    image: pircli-build:588ffbcf-ac3a-4408-8b47-1f9b41b1a682
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_train_dataset:?err}:/mnt/graph_inputs/train_dataset
  train_pipeline.evaluate:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVeQIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjAhldmFsdWF0ZZSMBmNvbmZpZ5R9lIwGaW5wdXRzlF2UKGgAjAlOb2RlSW5wdXSUk5QpgZR9lChoBYwTa3dhcmdzLnRlc3RfZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwLbm9kZV9vdXRwdXSUTowLZ3JhcGhfaW5wdXSUjAlzZW50ZW5jZXOUdWJ1YmgMKYGUfZQoaAWMEmt3YXJncy5wcmVkaWN0aW9uc5RoEIwJRElSRUNUT1JZlGgSaBQpgZR9lChoF2gAjA1Ob2RlT3V0cHV0UmVmlJOUKYGUfZQojAlub2RlX25hbWWUjBhpbmZlcl9waXBlbGluZS5zZW50aW1lbnSUjAtvdXRwdXRfbmFtZZSMBnJldHVybpR1YmgYTnVidWJljAdvdXRwdXRzlF2UaACMCk5vZGVPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjAlEQVRBRlJBTUWUdWJhjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwYZXhhbXBsZS5leGFtcGxlOmV2YWx1YXRllIwHcnVudGltZZSMCnB5dGhvbjozLjiUjAdjb2RldXJplE6MBWltYWdllIwxcGlyY2xpLWJ1aWxkOjU4OGZmYmNmLWFjM2EtNDQwOC04YjQ3LTFmOWI0MWIxYTY4MpR1YowJZnJhbWV3b3JrlE51Yi4=
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    depends_on:
      train_pipeline.infer_pipeline.sentiment:
        condition: service_completed_successfully
    image: pircli-build:588ffbcf-ac3a-4408-8b47-1f9b41b1a682
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
  train_pipeline.infer_pipeline.sentiment:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVgwIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjBhpbmZlcl9waXBlbGluZS5zZW50aW1lbnSUjAZjb25maWeUfZSMBmlucHV0c5RdlChoAIwJTm9kZUlucHV0lJOUKYGUfZQoaAWMBW1vZGVslIwGaW90eXBllIwERklMRZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwLbm9kZV9vdXRwdXSUaACMDU5vZGVPdXRwdXRSZWaUk5QpgZR9lCiMCW5vZGVfbmFtZZSMBXRyYWlulIwLb3V0cHV0X25hbWWUjAZyZXR1cm6UdWKMC2dyYXBoX2lucHV0lE51YnViaAwpgZR9lChoBYwJc2VudGVuY2VzlGgQjAlESVJFQ1RPUlmUaBJoFCmBlH2UKGgXaBkpgZR9lChoHIwaaW5mZXJfcGlwZWxpbmUudHJhbnNsYXRlXzGUaB6MBnJldHVybpR1YmggTnVidWJljAdvdXRwdXRzlF2UaACMCk5vZGVPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjAlESVJFQ1RPUlmUdWJhjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwZZXhhbXBsZS5leGFtcGxlOnNlbnRpbWVudJSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVyaZROjAVpbWFnZZSMMXBpcmNsaS1idWlsZDo1ODhmZmJjZi1hYzNhLTQ0MDgtOGI0Ny0xZjliNDFiMWE2ODKUdWKMCWZyYW1ld29ya5ROdWIu
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    depends_on:
      train_pipeline.infer_pipeline.translate_1:
        condition: service_completed_successfully
      train_pipeline.train:
        condition: service_completed_successfully
    image: pircli-build:588ffbcf-ac3a-4408-8b47-1f9b41b1a682
    volumes:
    - node_outputs:/mnt/node_outputs
  train_pipeline.infer_pipeline.translate_1:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVNQIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjBppbmZlcl9waXBlbGluZS50cmFuc2xhdGVfMZSMBmNvbmZpZ5R9lIwDa2V5lIwFdmFsdWWUc4wGaW5wdXRzlF2UKGgAjAlOb2RlSW5wdXSUk5QpgZR9lChoBYwGYXJncy4wlIwGaW90eXBllIwERklMRZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwLbm9kZV9vdXRwdXSUTowLZ3JhcGhfaW5wdXSUjA90cmFuc2xhdGVfbW9kZWyUdWJ1YmgOKYGUfZQoaAWMBmFyZ3MuMZRoEowJRElSRUNUT1JZlGgUaBYpgZR9lChoGU5oGowJc2VudGVuY2VzlHVidWJljAdvdXRwdXRzlF2UaACMCk5vZGVPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgSjAlESVJFQ1RPUlmUdWJhjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwZZXhhbXBsZS5leGFtcGxlOnRyYW5zbGF0ZZSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVyaZROjAVpbWFnZZSMMXBpcmNsaS1idWlsZDo1ODhmZmJjZi1hYzNhLTQ0MDgtOGI0Ny0xZjliNDFiMWE2ODKUdWKMCWZyYW1ld29ya5ROdWIu
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    image: pircli-build:588ffbcf-ac3a-4408-8b47-1f9b41b1a682
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_translate_model:?err}:/mnt/graph_inputs/translate_model
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
  train_pipeline.train:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVTQIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjAV0cmFpbpSMBmNvbmZpZ5R9lIwGaW5wdXRzlF2UaACMCU5vZGVJbnB1dJSTlCmBlH2UKGgFjAdkYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojAtub2RlX291dHB1dJRoAIwNTm9kZU91dHB1dFJlZpSTlCmBlH2UKIwJbm9kZV9uYW1llIwFY2xlYW6UjAtvdXRwdXRfbmFtZZSMBnJldHVybpR1YowLZ3JhcGhfaW5wdXSUTnVidWJhjAdvdXRwdXRzlF2UaACMCk5vZGVPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjARGSUxFlHViYYwKZW50cnlwb2ludJRoAIwKRW50cnlwb2ludJSTlCmBlH2UKIwHdmVyc2lvbpSMAnYxlIwHaGFuZGxlcpSMFWV4YW1wbGUuZXhhbXBsZTp0cmFpbpSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVyaZROjAVpbWFnZZSMMXBpcmNsaS1idWlsZDo1ODhmZmJjZi1hYzNhLTQ0MDgtOGI0Ny0xZjliNDFiMWE2ODKUdWKMCWZyYW1ld29ya5RoAIwJRnJhbWV3b3JrlJOUKYGUfZQoaAWMB2FkYXB0ZGyUaAd9lCiMDG1pbl9yZXBsaWNhc5RLAYwMbWF4X3JlcGxpY2FzlEsEdXVidWIu
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    depends_on:
      train_pipeline.clean:
        condition: service_completed_successfully
    image: pircli-build:588ffbcf-ac3a-4408-8b47-1f9b41b1a682
    volumes:
    - node_outputs:/mnt/node_outputs
version: '3.9'
volumes:
  node_outputs: {}
