services:
  train_pipeline:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - graph
    - gASV+wAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMC0dyYXBoT3V0cHV0lJOUKYGUfZQojARuYW1llIwIcmV0dXJuLjCUjAZpb3R5cGWUjARGSUxFlIwGc291cmNllGgBjApEYXRhU291cmNllJOUKYGUfZQojARub2RllIwFdHJhaW6UjAhzdWJncmFwaJROjAZvdXRwdXSUjAZyZXR1cm6UjAtncmFwaF9pbnB1dJROdWJ1YmgDKYGUfZQoaAaMCHJldHVybi4xlGgIjAlEQVRBRlJBTUWUaApoDCmBlH2UKGgPjAhldmFsdWF0ZZRoEU5oEowGcmV0dXJulGgUTnVidWJlLg==
    depends_on:
      train_pipeline.clean:
        condition: service_completed_successfully
      train_pipeline.evaluate:
        condition: service_completed_successfully
      train_pipeline.infer_pipeline.sentiment:
        condition: service_completed_successfully
      train_pipeline.infer_pipeline.translate_1:
        condition: service_completed_successfully
      train_pipeline.train:
        condition: service_completed_successfully
    image: pircli-build:6063df32-2483-4e2e-beee-944931c72937
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_train_dataset:?err}:/mnt/graph_inputs/train_dataset
    - ${INPUT_translate_model:?err}:/mnt/graph_inputs/translate_model
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
    - ${OUTPUT:?err}:/mnt/graph_outputs
  train_pipeline.clean:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASV1wEAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjAVjbGVhbpSMBmNvbmZpZ5R9lIwGaW5wdXRzlF2UaACMBUlucHV0lJOUKYGUfZQoaAWMB2RhdGFzZXSUjAZpb3R5cGWUjAlESVJFQ1RPUlmUjAZzb3VyY2WUaACMCkRhdGFTb3VyY2WUk5QpgZR9lCiMBG5vZGWUTowIc3ViZ3JhcGiUTowGb3V0cHV0lE6MC2dyYXBoX2lucHV0lIwNdHJhaW5fZGF0YXNldJR1YnViYYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjAlESVJFQ1RPUlmUdWJhjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwVZXhhbXBsZS5leGFtcGxlOmNsZWFulIwHcnVudGltZZSMCnB5dGhvbjozLjiUjAdjb2RldXJplE6MBWltYWdllIwxcGlyY2xpLWJ1aWxkOjYwNjNkZjMyLTI0ODMtNGUyZS1iZWVlLTk0NDkzMWM3MjkzN5R1YowJZnJhbWV3b3JrlE51Yi4=
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    image: pircli-build:6063df32-2483-4e2e-beee-944931c72937
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_train_dataset:?err}:/mnt/graph_inputs/train_dataset
  train_pipeline.evaluate:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVTwIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjAhldmFsdWF0ZZSMBmNvbmZpZ5R9lIwGaW5wdXRzlF2UKGgAjAVJbnB1dJSTlCmBlH2UKGgFjBNrd2FyZ3MudGVzdF9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojARub2RllE6MCHN1YmdyYXBolE6MBm91dHB1dJROjAtncmFwaF9pbnB1dJSMCXNlbnRlbmNlc5R1YnViaAwpgZR9lChoBYwSa3dhcmdzLnByZWRpY3Rpb25zlGgQjAlESVJFQ1RPUlmUaBJoFCmBlH2UKGgXjBhpbmZlcl9waXBlbGluZS5zZW50aW1lbnSUaBhOaBmMBnJldHVybpRoGk51YnViZYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjAlEQVRBRlJBTUWUdWJhjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwYZXhhbXBsZS5leGFtcGxlOmV2YWx1YXRllIwHcnVudGltZZSMCnB5dGhvbjozLjiUjAdjb2RldXJplE6MBWltYWdllIwxcGlyY2xpLWJ1aWxkOjYwNjNkZjMyLTI0ODMtNGUyZS1iZWVlLTk0NDkzMWM3MjkzN5R1YowJZnJhbWV3b3JrlE51Yi4=
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    depends_on:
      train_pipeline.infer_pipeline.sentiment:
        condition: service_completed_successfully
    image: pircli-build:6063df32-2483-4e2e-beee-944931c72937
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
  train_pipeline.infer_pipeline.sentiment:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVSgIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjBhpbmZlcl9waXBlbGluZS5zZW50aW1lbnSUjAZjb25maWeUfZSMBmlucHV0c5RdlChoAIwFSW5wdXSUk5QpgZR9lChoBYwFbW9kZWyUjAZpb3R5cGWUjARGSUxFlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojARub2RllIwFdHJhaW6UjAhzdWJncmFwaJROjAZvdXRwdXSUjAZyZXR1cm6UjAtncmFwaF9pbnB1dJROdWJ1YmgMKYGUfZQoaAWMCXNlbnRlbmNlc5RoEIwJRElSRUNUT1JZlGgSaBQpgZR9lChoF4waaW5mZXJfcGlwZWxpbmUudHJhbnNsYXRlXzGUaBlOaBqMBnJldHVybpRoHE51YnViZYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjAlESVJFQ1RPUlmUdWJhjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwZZXhhbXBsZS5leGFtcGxlOnNlbnRpbWVudJSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVyaZROjAVpbWFnZZSMMXBpcmNsaS1idWlsZDo2MDYzZGYzMi0yNDgzLTRlMmUtYmVlZS05NDQ5MzFjNzI5MzeUdWKMCWZyYW1ld29ya5ROdWIu
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    depends_on:
      train_pipeline.infer_pipeline.translate_1:
        condition: service_completed_successfully
      train_pipeline.train:
        condition: service_completed_successfully
    image: pircli-build:6063df32-2483-4e2e-beee-944931c72937
    volumes:
    - node_outputs:/mnt/node_outputs
  train_pipeline.infer_pipeline.translate_1:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVQgIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjBppbmZlcl9waXBlbGluZS50cmFuc2xhdGVfMZSMBmNvbmZpZ5R9lIwDa2V5lIwFdmFsdWWUc4wGaW5wdXRzlF2UKGgAjAVJbnB1dJSTlCmBlH2UKGgFjAZhcmdzLjCUjAZpb3R5cGWUjARGSUxFlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojARub2RllE6MCHN1YmdyYXBolE6MBm91dHB1dJROjAtncmFwaF9pbnB1dJSMD3RyYW5zbGF0ZV9tb2RlbJR1YnViaA4pgZR9lChoBYwGYXJncy4xlGgSjAlESVJFQ1RPUlmUaBRoFimBlH2UKGgZTmgaTmgbTmgcjAlzZW50ZW5jZXOUdWJ1YmWMB291dHB1dHOUXZRoAIwGT3V0cHV0lJOUKYGUfZQoaAWMBnJldHVybpRoEowJRElSRUNUT1JZlHViYYwKZW50cnlwb2ludJRoAIwKRW50cnlwb2ludJSTlCmBlH2UKIwHdmVyc2lvbpSMAnYxlIwHaGFuZGxlcpSMGWV4YW1wbGUuZXhhbXBsZTp0cmFuc2xhdGWUjAdydW50aW1llIwKcHl0aG9uOjMuOJSMB2NvZGV1cmmUTowFaW1hZ2WUjDFwaXJjbGktYnVpbGQ6NjA2M2RmMzItMjQ4My00ZTJlLWJlZWUtOTQ0OTMxYzcyOTM3lHVijAlmcmFtZXdvcmuUTnViLg==
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    image: pircli-build:6063df32-2483-4e2e-beee-944931c72937
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_translate_model:?err}:/mnt/graph_inputs/translate_model
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
  train_pipeline.train:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVHQIAAAAAAACMDHBpcmxpYi5ncmFwaJSMBE5vZGWUk5QpgZR9lCiMBG5hbWWUjAV0cmFpbpSMBmNvbmZpZ5R9lIwGaW5wdXRzlF2UaACMBUlucHV0lJOUKYGUfZQoaAWMB2RhdGFzZXSUjAZpb3R5cGWUjAlESVJFQ1RPUlmUjAZzb3VyY2WUaACMCkRhdGFTb3VyY2WUk5QpgZR9lCiMBG5vZGWUjAVjbGVhbpSMCHN1YmdyYXBolE6MBm91dHB1dJSMBnJldHVybpSMC2dyYXBoX2lucHV0lE51YnViYYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgQjARGSUxFlHViYYwKZW50cnlwb2ludJRoAIwKRW50cnlwb2ludJSTlCmBlH2UKIwHdmVyc2lvbpSMAnYxlIwHaGFuZGxlcpSMFWV4YW1wbGUuZXhhbXBsZTp0cmFpbpSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVyaZROjAVpbWFnZZSMMXBpcmNsaS1idWlsZDo2MDYzZGYzMi0yNDgzLTRlMmUtYmVlZS05NDQ5MzFjNzI5MzeUdWKMCWZyYW1ld29ya5RoAIwJRnJhbWV3b3JrlJOUKYGUfZQoaAWMB2FkYXB0ZGyUaAd9lCiMDG1pbl9yZXBsaWNhc5RLAYwMbWF4X3JlcGxpY2FzlEsEdXVidWIu
    - gASVpAAAAAAAAABdlCiMDHBpcmxpYi5ncmFwaJSMCkdyYXBoSW5wdXSUk5QpgZR9lCiMBG5hbWWUjA10cmFpbl9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlHViaAMpgZR9lChoBowPdHJhbnNsYXRlX21vZGVslGgIjARGSUxFlHViaAMpgZR9lChoBowJc2VudGVuY2VzlGgIjAlESVJFQ1RPUlmUdWJlLg==
    depends_on:
      train_pipeline.clean:
        condition: service_completed_successfully
    image: pircli-build:6063df32-2483-4e2e-beee-944931c72937
    volumes:
    - node_outputs:/mnt/node_outputs
version: '3.9'
volumes:
  node_outputs: {}
