services:
  train_pipeline:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - graph
    - gASV+QAAAAAAAABdlCiMCnBpcmxpYi5waXKUjAtHcmFwaE91dHB1dJSTlCmBlH2UKIwEbmFtZZSMCHJldHVybi4wlIwGaW90eXBllIwERklMRZSMBnNvdXJjZZRoAYwKRGF0YVNvdXJjZZSTlCmBlH2UKIwEbm9kZZSMBXRyYWlulIwIc3ViZ3JhcGiUTowGb3V0cHV0lIwGcmV0dXJulIwLZ3JhcGhfaW5wdXSUTnVidWJoAymBlH2UKGgGjAhyZXR1cm4uMZRoCIwJREFUQUZSQU1FlGgKaAwpgZR9lChoD4wIZXZhbHVhdGWUaBFOaBKMBnJldHVybpRoFE51YnViZS4=
    depends_on:
      train_pipeline.clean:
        condition: service_completed_successfully
      train_pipeline.evaluate:
        condition: service_completed_successfully
      train_pipeline.infer_pipeline.sentiment:
        condition: service_completed_successfully
      train_pipeline.infer_pipeline.translate_1:
        condition: service_completed_successfully
      train_pipeline.train:
        condition: service_completed_successfully
    image: pircli-build:fbb9b1d1-11ed-48a6-a70c-67a1f6c928a5
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_train_dataset:?err}:/mnt/graph_inputs/train_dataset
    - ${INPUT_translate_model:?err}:/mnt/graph_inputs/translate_model
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
    - ${OUTPUT:?err}:/mnt/graph_outputs
  train_pipeline.clean:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASV1QEAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojARuYW1llIwFY2xlYW6UjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwVZXhhbXBsZS5leGFtcGxlOmNsZWFulIwHcnVudGltZZSMCnB5dGhvbjozLjiUjAdjb2RldXJslE6MBWltYWdllIwxcGlyY2xpLWJ1aWxkOmZiYjliMWQxLTExZWQtNDhhNi1hNzBjLTY3YTFmNmM5MjhhNZR1YowJZnJhbWV3b3JrlE6MBmNvbmZpZ5R9lIwGaW5wdXRzlF2UaACMBUlucHV0lJOUKYGUfZQoaAWMB2RhdGFzZXSUjAZpb3R5cGWUjAlESVJFQ1RPUlmUjAZzb3VyY2WUaACMCkRhdGFTb3VyY2WUk5QpgZR9lCiMBG5vZGWUTowIc3ViZ3JhcGiUTowGb3V0cHV0lE6MC2dyYXBoX2lucHV0lIwNdHJhaW5fZGF0YXNldJR1YnViYYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgfjAlESVJFQ1RPUlmUdWJhdWIu
    - gASVogAAAAAAAABdlCiMCnBpcmxpYi5waXKUjApHcmFwaElucHV0lJOUKYGUfZQojARuYW1llIwNdHJhaW5fZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZR1YmgDKYGUfZQoaAaMD3RyYW5zbGF0ZV9tb2RlbJRoCIwERklMRZR1YmgDKYGUfZQoaAaMCXNlbnRlbmNlc5RoCIwJRElSRUNUT1JZlHViZS4=
    image: pircli-build:fbb9b1d1-11ed-48a6-a70c-67a1f6c928a5
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_train_dataset:?err}:/mnt/graph_inputs/train_dataset
  train_pipeline.evaluate:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVTQIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojARuYW1llIwIZXZhbHVhdGWUjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwYZXhhbXBsZS5leGFtcGxlOmV2YWx1YXRllIwHcnVudGltZZSMCnB5dGhvbjozLjiUjAdjb2RldXJslE6MBWltYWdllIwxcGlyY2xpLWJ1aWxkOmZiYjliMWQxLTExZWQtNDhhNi1hNzBjLTY3YTFmNmM5MjhhNZR1YowJZnJhbWV3b3JrlE6MBmNvbmZpZ5R9lIwGaW5wdXRzlF2UKGgAjAVJbnB1dJSTlCmBlH2UKGgFjBNrd2FyZ3MudGVzdF9kYXRhc2V0lIwGaW90eXBllIwJRElSRUNUT1JZlIwGc291cmNllGgAjApEYXRhU291cmNllJOUKYGUfZQojARub2RllE6MCHN1YmdyYXBolE6MBm91dHB1dJROjAtncmFwaF9pbnB1dJSMCXNlbnRlbmNlc5R1YnViaBspgZR9lChoBYwSa3dhcmdzLnByZWRpY3Rpb25zlGgfjAlESVJFQ1RPUlmUaCFoIymBlH2UKGgmjBhpbmZlcl9waXBlbGluZS5zZW50aW1lbnSUaCdOaCiMBnJldHVybpRoKU51YnViZYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgfjAlEQVRBRlJBTUWUdWJhdWIu
    - gASVogAAAAAAAABdlCiMCnBpcmxpYi5waXKUjApHcmFwaElucHV0lJOUKYGUfZQojARuYW1llIwNdHJhaW5fZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZR1YmgDKYGUfZQoaAaMD3RyYW5zbGF0ZV9tb2RlbJRoCIwERklMRZR1YmgDKYGUfZQoaAaMCXNlbnRlbmNlc5RoCIwJRElSRUNUT1JZlHViZS4=
    depends_on:
      train_pipeline.infer_pipeline.sentiment:
        condition: service_completed_successfully
    image: pircli-build:fbb9b1d1-11ed-48a6-a70c-67a1f6c928a5
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
  train_pipeline.infer_pipeline.sentiment:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVSAIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojARuYW1llIwYaW5mZXJfcGlwZWxpbmUuc2VudGltZW50lIwKZW50cnlwb2ludJRoAIwKRW50cnlwb2ludJSTlCmBlH2UKIwHdmVyc2lvbpSMAnYxlIwHaGFuZGxlcpSMGWV4YW1wbGUuZXhhbXBsZTpzZW50aW1lbnSUjAdydW50aW1llIwKcHl0aG9uOjMuOJSMB2NvZGV1cmyUTowFaW1hZ2WUjDFwaXJjbGktYnVpbGQ6ZmJiOWIxZDEtMTFlZC00OGE2LWE3MGMtNjdhMWY2YzkyOGE1lHVijAlmcmFtZXdvcmuUTowGY29uZmlnlH2UjAZpbnB1dHOUXZQoaACMBUlucHV0lJOUKYGUfZQoaAWMBW1vZGVslIwGaW90eXBllIwERklMRZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwEbm9kZZSMBXRyYWlulIwIc3ViZ3JhcGiUTowGb3V0cHV0lIwGcmV0dXJulIwLZ3JhcGhfaW5wdXSUTnVidWJoGymBlH2UKGgFjAlzZW50ZW5jZXOUaB+MCURJUkVDVE9SWZRoIWgjKYGUfZQoaCaMGmluZmVyX3BpcGVsaW5lLnRyYW5zbGF0ZV8xlGgoTmgpjAZyZXR1cm6UaCtOdWJ1YmWMB291dHB1dHOUXZRoAIwGT3V0cHV0lJOUKYGUfZQoaAWMBnJldHVybpRoH4wJRElSRUNUT1JZlHViYXViLg==
    - gASVogAAAAAAAABdlCiMCnBpcmxpYi5waXKUjApHcmFwaElucHV0lJOUKYGUfZQojARuYW1llIwNdHJhaW5fZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZR1YmgDKYGUfZQoaAaMD3RyYW5zbGF0ZV9tb2RlbJRoCIwERklMRZR1YmgDKYGUfZQoaAaMCXNlbnRlbmNlc5RoCIwJRElSRUNUT1JZlHViZS4=
    depends_on:
      train_pipeline.infer_pipeline.translate_1:
        condition: service_completed_successfully
      train_pipeline.train:
        condition: service_completed_successfully
    image: pircli-build:fbb9b1d1-11ed-48a6-a70c-67a1f6c928a5
    volumes:
    - node_outputs:/mnt/node_outputs
  train_pipeline.infer_pipeline.translate_1:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVQAIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojARuYW1llIwaaW5mZXJfcGlwZWxpbmUudHJhbnNsYXRlXzGUjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwZZXhhbXBsZS5leGFtcGxlOnRyYW5zbGF0ZZSMB3J1bnRpbWWUjApweXRob246My44lIwHY29kZXVybJROjAVpbWFnZZSMMXBpcmNsaS1idWlsZDpmYmI5YjFkMS0xMWVkLTQ4YTYtYTcwYy02N2ExZjZjOTI4YTWUdWKMCWZyYW1ld29ya5ROjAZjb25maWeUfZSMA2tleZSMBXZhbHVllHOMBmlucHV0c5RdlChoAIwFSW5wdXSUk5QpgZR9lChoBYwGYXJncy4wlIwGaW90eXBllIwERklMRZSMBnNvdXJjZZRoAIwKRGF0YVNvdXJjZZSTlCmBlH2UKIwEbm9kZZROjAhzdWJncmFwaJROjAZvdXRwdXSUTowLZ3JhcGhfaW5wdXSUjA90cmFuc2xhdGVfbW9kZWyUdWJ1YmgdKYGUfZQoaAWMBmFyZ3MuMZRoIYwJRElSRUNUT1JZlGgjaCUpgZR9lChoKE5oKU5oKk5oK4wJc2VudGVuY2VzlHVidWJljAdvdXRwdXRzlF2UaACMBk91dHB1dJSTlCmBlH2UKGgFjAZyZXR1cm6UaCGMCURJUkVDVE9SWZR1YmF1Yi4=
    - gASVogAAAAAAAABdlCiMCnBpcmxpYi5waXKUjApHcmFwaElucHV0lJOUKYGUfZQojARuYW1llIwNdHJhaW5fZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZR1YmgDKYGUfZQoaAaMD3RyYW5zbGF0ZV9tb2RlbJRoCIwERklMRZR1YmgDKYGUfZQoaAaMCXNlbnRlbmNlc5RoCIwJRElSRUNUT1JZlHViZS4=
    image: pircli-build:fbb9b1d1-11ed-48a6-a70c-67a1f6c928a5
    volumes:
    - node_outputs:/mnt/node_outputs
    - ${INPUT_translate_model:?err}:/mnt/graph_inputs/translate_model
    - ${INPUT_sentences:?err}:/mnt/graph_inputs/sentences
  train_pipeline.train:
    command:
    - python
    - -m
    - pirlib.backends.docker_batch
    - node
    - gASVGwIAAAAAAACMCnBpcmxpYi5waXKUjAROb2RllJOUKYGUfZQojARuYW1llIwFdHJhaW6UjAplbnRyeXBvaW50lGgAjApFbnRyeXBvaW50lJOUKYGUfZQojAd2ZXJzaW9ulIwCdjGUjAdoYW5kbGVylIwVZXhhbXBsZS5leGFtcGxlOnRyYWlulIwHcnVudGltZZSMCnB5dGhvbjozLjiUjAdjb2RldXJslE6MBWltYWdllIwxcGlyY2xpLWJ1aWxkOmZiYjliMWQxLTExZWQtNDhhNi1hNzBjLTY3YTFmNmM5MjhhNZR1YowJZnJhbWV3b3JrlGgAjAlGcmFtZXdvcmuUk5QpgZR9lChoBYwHYWRhcHRkbJSMBmNvbmZpZ5R9lCiMDG1pbl9yZXBsaWNhc5RLAYwMbWF4X3JlcGxpY2FzlEsEdXViaBt9lIwGaW5wdXRzlF2UaACMBUlucHV0lJOUKYGUfZQoaAWMB2RhdGFzZXSUjAZpb3R5cGWUjAlESVJFQ1RPUlmUjAZzb3VyY2WUaACMCkRhdGFTb3VyY2WUk5QpgZR9lCiMBG5vZGWUjAVjbGVhbpSMCHN1YmdyYXBolE6MBm91dHB1dJSMBnJldHVybpSMC2dyYXBoX2lucHV0lE51YnViYYwHb3V0cHV0c5RdlGgAjAZPdXRwdXSUk5QpgZR9lChoBYwGcmV0dXJulGgnjARGSUxFlHViYXViLg==
    - gASVogAAAAAAAABdlCiMCnBpcmxpYi5waXKUjApHcmFwaElucHV0lJOUKYGUfZQojARuYW1llIwNdHJhaW5fZGF0YXNldJSMBmlvdHlwZZSMCURJUkVDVE9SWZR1YmgDKYGUfZQoaAaMD3RyYW5zbGF0ZV9tb2RlbJRoCIwERklMRZR1YmgDKYGUfZQoaAaMCXNlbnRlbmNlc5RoCIwJRElSRUNUT1JZlHViZS4=
    depends_on:
      train_pipeline.clean:
        condition: service_completed_successfully
    image: pircli-build:fbb9b1d1-11ed-48a6-a70c-67a1f6c928a5
    volumes:
    - node_outputs:/mnt/node_outputs
version: '3.9'
volumes:
  node_outputs: {}
