# Copyright 2022 Petuum, Inc. All Rights Reserved.

graphs: list(include("graph"))
---
graph:
  name: str()
  nodes: list(include("node"))
  subgraphs: list(include("subgraph"))
  inputs: list(include("graph_input"))
  outputs: list(include("graph_output"))
---
node:
  name: str()
  entrypoint: include("entrypoint")
  framework: any(include("framework"), null())
  config: map()
  inputs: list(include("input"))
  outputs: list(include("output"))
---
subgraph:
  name: str()
  graph: str()
  inputs: list(include("input"))
  outputs: list(include("output"))
---
graph_input:
  name: str()
  iotype: str()
---
graph_output:
  name: str()
  iotype: str()
  source: include("datasource")
---
input:
  name: str()
  iotype: str()
  source: include("datasource")
---
output:
  name: str()
  iotype: str()
---
datasource:
  node: any(str(), null())
  subgraph: any(str(), null())
  output: any(str(), null())
  graph_input: any(str(), null())
---
framework:
  name: str()
  config: map()
---
entrypoint:
  version: str()
  handler: str()
  runtime: str()
  codeuri: any(str(), null())
  image: any(str(), null())
