# Copyright 2022 Petuum, Inc. All Rights Reserved.

graphs: map(include('graph'))
---
graph:
  name: str()
  id: str()
  nodes: map(include('node'))
  subgraphs: map(include("subgraph"))
  inputs: map(include("graph_input"))
  outputs: map(include("graph_output"))
  annotations: include('graph_annotation', required=False)
---
graph_annotation:
  author: any(str(), null())
  timestamp: any(str(), null())
  execution_mode: any(str(), null())
---
node:
  name: str()
  id: str()
  entrypoints: map(include('entrypoint'))
  configs:
    framework: any(include('framework'), null())
  inputs: map(include('input'))  # key is <input id>
  outputs: map(include('output'))  # key is <output id>
  annotations: include('node_annotation', required=False)
---
subgraph:
  name: str()
  id: str()
  graph_id: str()
  config: map()
  inputs: map(include("input"))  # key is <input id>
  outputs: map(include("output")) # key is <output id>
---
graph_input:
  name: str()
  id: str()
  meta: include('meta_data')
---
graph_output:
  name: str()
  id: str()
  source: include("datasource")
  meta: include('meta_data')
---
input:
  meta: include('meta_data')
  source: include('datasource')
---
output:
  id: str()
  meta: include('meta_data')
---
meta_data:  # for backend data marshalling
  type: str()
  schema:
    type: any(str(), null())
    name: any(str(), null())
    fields:
    - name: any(str(), null())
      type: any(str(), null())
---
datasource:
  node_id: any(str(), null())
  subgraph_id: any(str(), null())
  output_id: any(str(), null())
  graph_input_id: any(str(), null())
---
node_annotation:
  type: any(str(), null())
  version: any(str(), null())
---
framework:
  name: str()
  version: any(str(), null())
  config: map()
---
entrypoint:
  version: str()
  codeurl: any(str(), null())
  handler: str()
  id: str()
  env:
    image: any(str(), null())
    dependencies: any(map(), null())
  runtime: str()