name: PIRLib Actions

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Running Units Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install --progress-bar off pytest==5.1.3

      - name: Install PirLib
        run: pip install --progress-bar off .
        
      - name: Install example dependencies
        run: pip install -r example/requirements.txt

      - name: Test with pytest
        run: pytest tests/